### ISSUE TITLE
Player lost connection....

### ISSUE THREAD

**Issue by slwoodward** [hwoodward/Remote-Card-Games#109]
**Describe the bug**
Player 4 ended turn, player 5 began turn,  when player 5 turn ended player 4's display did not show the discard and player 5 name remained in bold on player 4 display.  Everyone else saw game advancing as it should.  When player 4's turn came again (this was a 5 player game) she couldn't play, and her name did not become bold.  No one else could play either.  CMD window did not have any informative error messages.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hwoodward** [comment]
When we saw this with Dad and I got logs and I got
error: uncaptured python exception, closing channel <server.PlayerChannel.PlayerChannel 99.144.119.99:50496 at 0x3aa3de38370> (<class 'TimeoutError'>:[Errno 110] Connection timed out [/home/woodstaradmin/opt/python-3.8.1/lib/python3.8/asynchat.py|handle_read|117] [/home/woodstaradmin/opt/python-3.8.1/lib/python3.8/asyncore.py|recv|371])

**Comment by hwoodward** [comment]
Having examined this - the timeout error we are seeing is what is logged when the client actually finally disconnects with the server. After that it appears the client does disconnect properly, and if they were the last player the game is stopped properly.

I cannot remember for sure if after waiting for the problem player to time out we were able to continue - but I think we were not. There is something else that is causing the hanging player to get stuck and putting the server in an unrecoverable state.

**Comment by slwoodward** [comment]
Screen text from game on May 17 with lost player connection:

...
Enter the ruleset[HandAndFoot]
HandAndFoot
Select a display name: Ted
Connected to the server
Server disconnected
Traceback (most recent call last):
  File "RunClient.py", line 56, in <module>
  File "RunClient.py", line 43, in RunClient
  File "site-packages\PodSixNet\Connection.py", line 31, in Pump
  File "site-packages\PodSixNet\Connection.py", line 31, in <listcomp>
  File "client\Controller.py", line 216, in Network_disconnected
NameError: name 'exit' is not defined
[4568] Failed to execute script RunClient

**Comment by hwoodward** [comment]
We are able to reproduce a person hanging the game by turning wifi off. However that recovers if the wifi is turned back on before the connection times out. If the connection times out on either side we should close the connection.

On the server side a timeout should call the close methods that lead to disconnecting the player, but observations don't appear to be showing the turn being advanced properly. Debug logging should probably be added to enable debugging and testing

On the client side the timeout appears to call Network_disconnected, but instead of calling Conection.close it calls exit, which is not a python method (I must have been thinking of Java when I wrote it).
